// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Witnessing.Client.DataModel;
//
//    var authenticationResult = AuthenticationResult.FromJson(jsonString);

namespace Witnessing.Client.DataModel
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class AuthenticationResultBody
    {
        public static AuthenticationResultUser FromJson(string json) => JsonConvert.DeserializeObject<AuthenticationResultUser>(json, Witnessing.Client.DataModel.Converter.Settings);
    }
}
